name: Job Backend CI

on:
  push:
    branches: [ master ]
    paths:
        - 'backend/JobServer/**'
  pull_request:
    branches: [ master ]
    paths:
        - 'backend/JobServer/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd backend/JobServer
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        cd backend/JobServer
        pytest test.py